version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - mern-network

  api-gateway:
    build:
      context: ./backend
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - INTERNAL_SECRET=thwnjfiw12n3j4n089cjnn3nslpi34
      - JWT_SECRET=my_secret_key_for_shop_ma_project
      - AUTH_SERVICE_URL=http://auth-service:5000
      - PRODUCT_SERVICE_URL=http://product-service:5001
      - CART_SERVICE_URL=http://cart-service:5003
      - FAVORITE_SERVICE_URL=http://favorite-service:5002
      - ORDER_SERVICE_URL=http://order-service:5004
      - NOTIFICATION_SERVICE_URL=http://notifications-service:5005
      - PASSWORD_GENERATOR_URL=http://password-generator:5005
    depends_on:
      - auth-service
      - product-service
      - cart-service
      - favorite-service
      - order-service
      - notifications-service
      - password-generator
    networks:
      - mern-network

  auth-service:
    build:
      context: ./backend
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    environment:
      - PORT=5000
      - MONGO_URI_USER_DB=mongodb://mongodb:27017/users
      - INTERNAL_SECRET=thwnjfiw12n3j4n089cjnn3nslpi34
      - JWT_SECRET=my_secret_key_for_shop_ma_project
    depends_on:
      - mongodb
    networks:
      - mern-network

  product-service:
    build:
      context: ./backend
      dockerfile: product-service/Dockerfile
    container_name: product-service
    environment:
      - PORT=5001
      - MONGO_URI_PRODUCTS_DB=mongodb://mongodb:27017/products
      - INTERNAL_SECRET=thwnjfiw12n3j4n089cjnn3nslpi34
    depends_on:
      - mongodb
    networks:
      - mern-network

  cart-service:
    build:
      context: ./backend
      dockerfile: cart-service/Dockerfile
    container_name: cart-service
    environment:
      - PORT=5003
      - MONGO_URI_CART_DB=mongodb://mongodb:27017/cart
      - INTERNAL_SECRET=thwnjfiw12n3j4n089cjnn3nslpi34
      - PRODUCT_SERVICE=http://product-service:5001
    depends_on:
      - mongodb
    networks:
      - mern-network

  favorite-service:
    build:
      context: ./backend
      dockerfile: favorite-service/Dockerfile
    container_name: favorite-service
    environment:
      - PORT=5002
      - MONGO_URI_FAVORITES_DB=mongodb://mongodb:27017/favorites
      - INTERNAL_SECRET=thwnjfiw12n3j4n089cjnn3nslpi34
      - PRODUCT_SERVICE=http://product-service:5001
    depends_on:
      - mongodb
    networks:
      - mern-network

  order-service:
    build:
      context: ./backend
      dockerfile: order-service/Dockerfile
    container_name: order-service
    environment:
      - PORT=5004
      - MONGO_URI_ORDERS_DB=mongodb://mongodb:27017/orders
      - INTERNAL_SECRET=thwnjfiw12n3j4n089cjnn3nslpi34
      - RABBITMQ_URL=amqp://rabbitmq
      - CART_SERVICE=http://cart-service:5003
      - PRODUCT_SERVICE=http://product-service:5001
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - mern-network

  notifications-service:
    build:
      context: ./backend
      dockerfile: notifications-service/Dockerfile
    container_name: notifications-service
    environment:
      - PORT=5005
      - MONGO_URI_NOTIFICATIONS_DB=mongodb://mongodb:27017/notifications
      - INTERNAL_SECRET=thwnjfiw12n3j4n089cjnn3nslpi34
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - mern-network

  password-generator:
    build:
      context: ./backend
      dockerfile: passwordGenerator-service/Dockerfile
    container_name: password-generator
    environment:
      - PORT=5005
    networks:
      - mern-network

volumes:
  mongo-data:

networks:
  mern-network:
    driver: bridge
